# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            a,z
tagline:          chronicles of anton zuiker
url:              http://zuiker.com
paginate:         1
baseurl:          http://mistersugar.github.io/poole/
author:
  name:           Anton Zuiker
  url:            http://mistersugar.com
  email:          anton@zuiker.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
